version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "v1r3n"
      - "c4lm"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
